
package clean_food;

import clean_food.Menu;
import static com.oracle.jrockit.jfr.ContentType.Bytes;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.util.Date;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.*;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;
import java.util.Collections;

public class orderfood extends javax.swing.JFrame {

    private Connection con = null;
    private ResultSet rs = null;
    private PreparedStatement pst = null;
    private Object ImgPath;
    String filename = null;
    byte[] person_image = null;
    private int i;
    
    public orderfood() {
        initComponents();
        
        con=Connect.ConnectDB();
        ShowDataToForm();
        ShowDataToForm1();
        ShowDataToForm2();
        
        setIcon();
        
        
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
    }
    
    
    private void setIcon(){
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("123.png")));
         
     }
    
    
    public void ShowDataToForm(){
        String sql="SELECT ProductID as 'ลำดับ',ProductName as 'ชื่อเมนู',Price as 'ราคา',gobbet as 'จำนวน',put as 'ภาชนะ',Category as 'เพิ่มเติม'\n"
                + "FROM list_menu ";
        try {
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            tbproduct_list.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(orderfood.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    public void ShowDataToForm2(){
        String sql="SELECT ProductID as 'ลำดับ',ProductName as 'ชื่อเมนู',Price as 'ราคา'\n"
                + "FROM menu_drink ";
        try {
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            tbproductdrink.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(orderfood.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    
    
    public void ShowDataToForm1(){
        String sql="SELECT ProductID as 'ลำดับ',ProductName as 'ชื่อเมนู',Price as 'ราคา'\n"
                + "FROM menu_food ";
        try {
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            tbproductmenu.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(orderfood.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        T1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbproductdrink = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbproductmenu = new javax.swing.JTable();
        txt_name = new javax.swing.JTextField();
        txt_price = new javax.swing.JTextField();
        txt_cate1 = new javax.swing.JTextField();
        lbl_image3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_search1 = new javax.swing.JTextField();
        txt_search = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        gobbet = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        put = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_sum = new javax.swing.JTextField();
        gobbet1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_cate2 = new javax.swing.JTextField();
        txt_price1 = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_name1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Ton1 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbproduct_list = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        Ton2 = new javax.swing.JTextField();
        txt_search2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        put1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton33 = new javax.swing.JButton();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("โปรแกรมระบบร้าน Food & Restaurant Apps");
        setAlwaysOnTop(true);
        setFocusable(false);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(900, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(204, 102, 0));
        jTabbedPane1.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jTabbedPane1.setOpaque(true);
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(520, 484));

        jPanel2.setPreferredSize(new java.awt.Dimension(830, 670));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        T1.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        T1.setText("โต๊ะที่ 1");
        T1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T1ActionPerformed(evt);
            }
        });
        jPanel2.add(T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, 80, 40));

        jButton2.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jButton2.setText("กลับสู่หน้าระบบงาน");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 590, -1, -1));

        tbproductdrink.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        tbproductdrink.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbproductdrink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbproductdrinkMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbproductdrink);
        if (tbproductdrink.getColumnModel().getColumnCount() > 0) {
            tbproductdrink.getColumnModel().getColumn(0).setResizable(false);
            tbproductdrink.getColumnModel().getColumn(1).setResizable(false);
            tbproductdrink.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 420, 200));

        tbproductmenu.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        tbproductmenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title1", "Title2", "Title3"
            }
        ));
        tbproductmenu.setOpaque(false);
        tbproductmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbproductmenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbproductmenuMouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(tbproductmenu);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 419, 210));

        txt_name.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jPanel2.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 120, -1));

        txt_price.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        txt_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_priceActionPerformed(evt);
            }
        });
        jPanel2.add(txt_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 120, -1));

        txt_cate1.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jPanel2.add(txt_cate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 120, -1));

        lbl_image3.setAutoscrolls(true);
        lbl_image3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl_image3.setOpaque(true);
        jPanel2.add(lbl_image3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 240, 170));

        jLabel2.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jLabel2.setText("ชื่อเมนู :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 50, -1));

        jLabel3.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jLabel3.setText("ราคา :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 40, -1));

        jLabel4.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jLabel4.setText("เพิ่มเติม :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 310, 50, -1));

        txt_search1.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        txt_search1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_search1KeyReleased(evt);
            }
        });
        jPanel2.add(txt_search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 335, 380, 25));

        txt_search.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        jPanel2.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 380, 25));

        jLabel14.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jLabel14.setText("ค้นหา :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 20));

        jLabel16.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jLabel16.setText("ค้นหา :");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 331, -1, 20));

        gobbet.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jPanel2.add(gobbet, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 120, 25));

        jLabel6.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jLabel6.setText("จำนวน :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 50, -1));

        put.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        put.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "จาน", "ห่อ", "แก้ว" }));
        jPanel2.add(put, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 280, 60, 25));

        jLabel21.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jLabel21.setText("บาท");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, 30, -1));

        jLabel19.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ข้อมูลรายการเครื่องดื่ม", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("TH SarabunPSK", 1, 18))); // NOI18N
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 480, 290));

        jLabel46.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ข้อมูลรายการอาหาร", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("TH SarabunPSK", 1, 18))); // NOI18N
        jPanel2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 480, 290));

        jLabel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "การทำรายการ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("TH SarabunPSK", 1, 18))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 300, 410));

        jLabel17.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "เลือกที่นั่ง", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("TH SarabunPSK", 1, 18))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 320, 160));

        jLabel24.setIcon(new javax.swing.ImageIcon("D:\\My Documents\\Downloads\\greentea-2.jpg")); // NOI18N
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel24.setPreferredSize(new java.awt.Dimension(890, 630));
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("สั่งเมนูอาหาร", jPanel2);

        jTabbedPane2.setBackground(new java.awt.Color(204, 102, 0));
        jTabbedPane2.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jTabbedPane2.setOpaque(true);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        area.setColumns(20);
        area.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        area.setRows(5);
        area.setPreferredSize(new java.awt.Dimension(222, 109));
        jScrollPane5.setViewportView(area);

        jPanel3.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 350, 240));

        jButton5.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jButton5.setText("ใบเสร็จ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 70, 36));

        jButton3.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jButton3.setText("ลบ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, 60, 30));

        jButton1.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jButton1.setText("แก้ไข");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 60, 30));

        jButton34.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jButton34.setText("บันทึกรายการ");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 275, 101, 30));

        jButton6.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jButton6.setText("ปริ้น");
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 70, 30));

        jLabel1.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jLabel1.setText("ราคารวม :");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, -1, -1));

        txt_sum.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jPanel3.add(txt_sum, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 110, 30));

        gobbet1.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        gobbet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobbet1ActionPerformed(evt);
            }
        });
        jPanel3.add(gobbet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 188, 110, 30));

        jLabel12.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jLabel12.setText("จำนวน :");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 188, -1, -1));

        jLabel11.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jLabel11.setText("เพิ่มเติม :");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 224, -1, -1));

        txt_cate2.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        txt_cate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cate2ActionPerformed(evt);
            }
        });
        jPanel3.add(txt_cate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 224, 110, 30));

        txt_price1.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jPanel3.add(txt_price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 152, 110, 30));
        jPanel3.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 110, 30));

        jLabel9.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jLabel9.setText("ราคา :");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 152, -1, -1));

        jLabel8.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jLabel8.setText("ชื่อเมนู :");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 116, -1, -1));

        txt_name1.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jPanel3.add(txt_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 116, 110, 30));

        jLabel5.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jLabel5.setText("ลำดับ :");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 86, -1, -1));

        jLabel10.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jLabel10.setText("บาท");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 152, -1, -1));
        jPanel3.add(Ton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 110, 30));

        jButton7.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jButton7.setText("ราคารวม");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 370, 80, 30));

        tbproduct_list.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        tbproduct_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ชื่อเมนู", "ราคา", "จำนวน", "ภาชนะ", "เพิ่มเติม"
            }
        ));
        tbproduct_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbproduct_listMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbproduct_list);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 480, 190));

        jButton4.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jButton4.setText("กลับสู่หน้าระบบงาน");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 730, -1, -1));
        jPanel3.add(Ton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 450, 110, 30));

        txt_search2.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        txt_search2.setVerifyInputWhenFocusTarget(false);
        txt_search2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_search2ActionPerformed(evt);
            }
        });
        txt_search2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_search2KeyReleased(evt);
            }
        });
        jPanel3.add(txt_search2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 430, -1));

        jLabel15.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jLabel15.setText("บาท");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 410, -1, -1));

        put1.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jPanel3.add(put1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 30, 20));

        jLabel7.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jLabel7.setText("ค้นหา :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel18.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ข้อมูลรายการที่สั่ง", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("TH SarabunPSK", 1, 18))); // NOI18N
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 522, 306));

        jLabel20.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ข้อมูลใบเสร็จ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("TH SarabunPSK", 1, 18))); // NOI18N
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 326, 458, 274));

        jLabel23.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ข้อมูลอาหาร", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("TH SarabunPSK", 1, 18))); // NOI18N
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(573, 10, 300, 344));

        jButton33.setText("คิดเงิน");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 450, 80, 30));

        jLabel84.setText("เงินที่ได้รับ :");
        jPanel3.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 416, -1, -1));

        jLabel85.setText("เงินทอน :");
        jPanel3.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 456, -1, -1));

        jLabel86.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jLabel86.setText("บาท");
        jPanel3.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 370, -1, -1));

        jLabel87.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jLabel87.setText("บาท");
        jPanel3.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 450, 30, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon("D:\\My Documents\\Downloads\\greentea-2.jpg")); // NOI18N
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 630));

        jTabbedPane2.addTab("โต๊ะที่ 1", jPanel3);

        jTabbedPane1.addTab("รายการโต๊ะ", jTabbedPane2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 900, 690));

        jLabel78.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jLabel78.setText("Clean Food Programs");
        getContentPane().add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 110, -1));

        jLabel79.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clean_food/123.png"))); // NOI18N
        getContentPane().add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 30, 30));

        jLabel77.setBackground(new java.awt.Color(153, 153, 153));
        jLabel77.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jLabel77.setText("   - ");
        jLabel77.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel77.setOpaque(true);
        jLabel77.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel77MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 30, 40));

        jLabel50.setBackground(new java.awt.Color(255, 51, 51));
        jLabel50.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        jLabel50.setText("   X");
        jLabel50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel50.setOpaque(true);
        jLabel50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel50MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 40, 40));

        jLabel25.setBackground(new java.awt.Color(204, 102, 0));
        jLabel25.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel25.setOpaque(true);
        jLabel25.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel25MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel25MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 40));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        area.setText("****************************************************"+"\n\n");
        area.setText(area.getText()+"*        โปรแกรมระบบร้าน Food & Resturant apps       *"+"\n\n");
        area.setText(area.getText()+"                   "+"*        (ใบเสร็จรับเงิน)         *"+"\n\n");
        area.setText(area.getText()+"****************************************************"+"");

        Date obj = new Date();

        String date = obj.toString();

        area.setText(area.getText()+"\n                "+date+"\n");
        area.setText(area.getText()+"     "+"ชื่อเมนู"+"                   ");
        area.setText(area.getText()+"ราคา"+"      ");
        area.setText(area.getText()+"จำนวน"+"    ");
        area.setText(area.getText()+"หน่วย"+" ");
        area.setText(area.getText()+"\n");
        area.setText(area.getText()+"     "+txt_name1.getText()+"                      ");
        area.setText(area.getText()+txt_price1.getText()+"      ");
        area.setText(area.getText()+"       "+gobbet1.getText());
        area.setText(area.getText()+"       "+put1.getText());
        area.setText(area.getText()+"\n\n");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
     
        try{
            String sql="Select sum(Price*gobbet) from list_menu";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
               String sum = rs.getString("sum(Price*gobbet)");
               txt_sum.setText(sum); 
            }
        }catch(Exception e){
           JOptionPane.showMessageDialog(null, e); 
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Menu field= new Menu();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void gobbet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobbet1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gobbet1ActionPerformed

    private void txt_cate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cate2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cate2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        deleteRecord();
    }//GEN-LAST:event_jButton3ActionPerformed

    public void deleteRecord() {
        String id = txt_id.getText();
        String sql ="delete from list_menu WHERE ProductID='" + id + "'";
        try {
            Connection c = Connect.ConnectDB();
            if (pst.executeUpdate(sql) != -1) {
                JOptionPane.showMessageDialog(this, "ลบข้อมูลเรียบร้อย");
                ShowDataToForm();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
    private void txt_search2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search2KeyReleased
        DefaultTableModel table = (DefaultTableModel) tbproduct_list.getModel();
        String search = txt_search2.getText();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(table);
        tbproduct_list.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_txt_search2KeyReleased

    private void txt_search2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_search2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_search2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{

            String value1=txt_id.getText();
            String value2= txt_name1.getText();
            String value3= txt_price1.getText();
            
            String value4= gobbet1.getText();
            String value5= txt_cate2.getText();

            String sql="UPDATE list_menu SET ProductID = '"+value1+"',ProductName ='"+value2+"',Price ='"+value3+"',gobbet ='"+value4+"',Category ='"+value5+"' WHERE ProductID='"+value1+"' ";
            pst=con.prepareStatement(sql);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "แก้ไขเรียบร้อย", "แก้ไข", JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        ShowDataToForm();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbproduct_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbproduct_listMouseClicked
        try {
            int row=tbproduct_list.getSelectedRow();
            String selectId=tbproduct_list.getValueAt(row,0).toString();
            String sql="select * from list_menu where ProductID='"+selectId+"'";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
               
                String add1=rs.getString("ProductID");
                txt_id.setText(add1);
                String add2=rs.getString("ProductName");
                txt_name1.setText(add2);
                int add3=rs.getInt("Price");
                txt_price1.setText(add3+"");
                String add4=rs.getString("gobbet");
                gobbet1.setText(add4);
                String add5=rs.getString("put");
                put1.setText(add5);
                String add6=rs.getString("Category");
                txt_cate2.setText(add6);
              
            }
        } catch (SQLException ex) {
            Logger.getLogger(orderfood.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbproduct_listMouseClicked

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        DefaultTableModel table = (DefaultTableModel) tbproductmenu.getModel();
        String search = txt_search.getText();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(table);
        tbproductmenu.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_txt_searchKeyReleased

    private void txt_search1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search1KeyReleased
        DefaultTableModel table = (DefaultTableModel) tbproductdrink.getModel();
        String search = txt_search1.getText();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(table);
        tbproductdrink.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_txt_search1KeyReleased

    private void tbproductmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbproductmenuMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tbproductmenuMouseEntered

    private void tbproductmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbproductmenuMouseClicked
        try {
            int row=tbproductmenu.getSelectedRow();
            String selectId=tbproductmenu.getValueAt(row,0).toString();
            String sql="select * from menu_food where ProductID='"+selectId+"'";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){

                String add1=rs.getString("ProductName");
                txt_name.setText(add1);
                int add2=rs.getInt("Price");
                txt_price.setText(add2+"");

                byte[] add3=rs.getBytes("image");

                ImageIcon imageIcon = new ImageIcon(new ImageIcon(add3).getImage().getScaledInstance(lbl_image3.getWidth(),lbl_image3.getHeight(),Image.SCALE_SMOOTH));
                lbl_image3.setIcon(imageIcon);
            }
        } catch (SQLException ex) {
            Logger.getLogger(orderfood.class.getName()).log(Level.SEVERE, null, ex);
        }
        ShowDataToForm1();
    }//GEN-LAST:event_tbproductmenuMouseClicked

    private void tbproductdrinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbproductdrinkMouseClicked
        try {
            int row=tbproductdrink.getSelectedRow();
            String selectId=tbproductdrink.getValueAt(row,0).toString();
            String sql="select * from menu_drink where ProductID='"+selectId+"'";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){

                String add1=rs.getString("ProductName");
                txt_name.setText(add1);
                int add2=rs.getInt("Price");
                txt_price.setText(add2+"");

                byte[] add4=rs.getBytes("image");

                ImageIcon imageIcon = new ImageIcon(new ImageIcon(add4).getImage().getScaledInstance(lbl_image3.getWidth(),lbl_image3.getHeight(),Image.SCALE_SMOOTH));
                lbl_image3.setIcon(imageIcon);
            }
        } catch (SQLException ex) {
            Logger.getLogger(orderfood.class.getName()).log(Level.SEVERE, null, ex);
        }
        ShowDataToForm2();
    }//GEN-LAST:event_tbproductdrinkMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Menu field= new Menu();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void T1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T1ActionPerformed
       try{
            String sql="insert into list_menu (ProductName,Price,gobbet,put,Category)values(?,?,?,?,?)";
            pst=con.prepareStatement(sql);
           
            pst.setString(1, txt_name.getText());
            pst.setString(2, txt_price.getText());
            pst.setString(3, gobbet.getText());
             pst.setString(4, put.getSelectedItem().toString());
             pst.setString(5, txt_cate1.getText());
            pst.execute();
            JOptionPane.showMessageDialog(this, "บันทึก","บันทึกเรียบร้อย",JOptionPane.INFORMATION_MESSAGE);
            ShowDataToForm();
            clearData();
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_T1ActionPerformed
        
    
    
    private void txt_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_priceActionPerformed

    private void jLabel50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel50MouseClicked

        System.exit(0);

    }//GEN-LAST:event_jLabel50MouseClicked

    private void jLabel77MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel77MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel77MouseClicked

    private void jLabel25MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseDragged
         Point P = evt.getLocationOnScreen();
        this.setLocation(P);
    }//GEN-LAST:event_jLabel25MouseDragged

    private void jLabel25MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel25MouseMoved

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        try {
            String query = "insert into list_bay(ProductName,Price,gobbet,put)values(?,?,?,?)";
            pst = con.prepareStatement(query);

            pst.setString(1, txt_name1.getText());
            pst.setString(2, txt_price1.getText());
            pst.setString(3, gobbet1.getText());
            pst.setString(4, put1.getText());
            pst.execute();
            JOptionPane.showMessageDialog(this, "บันทึกเรียบร้อย", "บันทึก", JOptionPane.INFORMATION_MESSAGE);

            clearData();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        
         int T01 = Integer.parseInt(txt_sum.getText());
             int T02 = Integer.parseInt(Ton1.getText());
         int N1 = T01;
         int N2 = T02;
         int TATOL = N2-N1;
         int B1 = TATOL ;
            
            Ton2.setText (String.valueOf(B1));
        
        
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(orderfood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(orderfood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(orderfood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(orderfood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new orderfood().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton T1;
    private javax.swing.JTextField Ton1;
    private javax.swing.JTextField Ton2;
    private javax.swing.JTextArea area;
    private javax.swing.JTextField gobbet;
    private javax.swing.JTextField gobbet1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lbl_image3;
    private javax.swing.JComboBox put;
    private javax.swing.JLabel put1;
    private javax.swing.JTable tbproduct_list;
    private javax.swing.JTable tbproductdrink;
    private javax.swing.JTable tbproductmenu;
    private javax.swing.JTextField txt_cate1;
    private javax.swing.JTextField txt_cate2;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_name1;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_price1;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_search1;
    private javax.swing.JTextField txt_search2;
    private javax.swing.JTextField txt_sum;
    // End of variables declaration//GEN-END:variables
private void clearData() {
      
        txt_name1.setText("");
        txt_price1.setText("");
        txt_cate2.setText("");
        gobbet.setText("");
    }


}
